import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: {
    default: "MdShop | Toko Online Portofolio Ahmad Zidni",
    template: "%s | Toko Online Portofolio Ahmad Zidni",
  },
  description: "Generated by create next app",
  icons: [
    {
      url: "/logo.svg",
      href: "/logo.svg",
    },
  ],
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
        <NextTopLoader showSpinner={false} />
        {children}
      </body>
    </html>
  );
}
